"""
Module for editing/parsing .ss files generated by mfold.
"""

def parse(file_name):
    """Function for parse ss file and gives tuples with first
        and last column on output"""
    read_data = []
    with open(file_name, "r") as ss_file:
        for line in ss_file.readlines():
            splited = line.split()
            read_data.append([int(splited[0]), int(splited[-1])])
    return read_data

def to_normal():
    """
    Creates files with parsed data from all templates
    """
    for name in ('miR-122', 'miR-155', 'miR-21', 'miR-30a', 'miR-31'):
        with open(name, "w") as new_file:
            for elem in parse(name + ".ss"):
                new_file.write(" ".join(elem)+"\n")

def parse_score(name):
    """
    Parses files with score to list of tuple and score value
    """
    data = []
    with open(name) as score_file:
        for line in score_file:
            number, pair, score = line.split()
            data.append(([int(number), int(pair)], score))
    return data
