"""Offtarget tables

Revision ID: 58642e4678bd
Revises: 2c61bfbf51aa
Create Date: 2015-09-10 17:41:02.584707

"""

# revision identifiers, used by Alembic.
revision = '58642e4678bd'
down_revision = '2c61bfbf51aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_mrna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.Unicode(length=15), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.Unicode(length=15), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utr')
    op.drop_table('human_mrna')
    ### end Alembic commands ###
