#!/bin/bash

# Sometimes psql returns TCP connection error, but it works when command is
# just repeated one time more.
# Probably it's a problem with container linking.
until psql -U postgres -h $DB_PORT_5432_TCP_ADDR < /opt/shmir/shmirdesignercreate.sql &> /dev/null
do
    sleep 0.1
done

shmir-db-manage upgrade
shmir-db-seed
