#!/bin/bash

BROKER_ARG="-b amqp://guest@\$RABBITMQ_PORT_5672_TCP_ADDR//"

fig run --rm shmir /bin/bash -c "celery purge $BROKER_ARG -f"
fig run --rm shmir /bin/bash -c "celery amqp queue.purge $BROKER_ARG design"
fig run --rm shmir /bin/bash -c "celery amqp queue.purge $BROKER_ARG score"
fig run --rm shmir /bin/bash -c "celery amqp queue.purge $BROKER_ARG subtasks"
fig run --rm shmir /bin/bash -c "celery amqp queue.purge $BROKER_ARG blast"
fig run --rm redis /bin/bash -c "redis-cli FLUSHALL"
fig run --rm shmir /bin/bash -c "find src -name \"*.pyc\" -exec rm -rf {} \;"
